### PR TITLE
Update specification to better support derivative markets

### PR DESCRIPTION
**Pull request by trestrantham**

### CODE REVIEW

**Comment by ngauthier** [comment]
This is great. Only a few comments:

1. Maybe have the market `type` description first, before base and quote and their types.
2. Is there a clearer way to say "one of these is required" for volume and volume_quote? Maybe having a required section, then a "One of" section for groups of fields, then an optional section?
3. Is it worth grouping subtype? E.g. "These are valid subtypes for derivative markets: ..., These are valid subtypes for spot markets: ...". That way a spot market with subtype ["future"] would not be allowed. But then in the future maybe we have spot subtypes like `on-chain` or `off-chain` or `atomic` (just throwing out random ideas here) and these wouldn't be applicable to indices or derivatives? Trying to think ahead to how the auditor would check this stuff.

**Comment by trestrantham** [comment]
@ngauthier I agree and reorganized these changes to address all 3 points.

**Comment by trestrantham** [comment]
[Add versioning to adapter spec and ingestion](https://trello.com/c/nEl5TwkR/722-add-versioning-to-adapter-spec-and-ingestion)

**Comment by trestrantham** [comment]
@ngauthier Re-requested for a final look over before merging and publishing this as `1.0`.

**Pull request merged**
