### PR TITLE
Add specification for tickers

### PR DESCRIPTION
**Pull request by trestrantham**
This creates a specification to allow ingestion of market tickers from exchange integrations. Tickers should be provided for a single market at a time (via the `market` parameter). Implementing the ticker integration is **discouraged** in favor of trades.

### CODE REVIEW

**Comment by trestrantham** [comment]
[Ingest, Store, and Display Data from 40+ Exchanges Via Tickers](https://trello.com/c/8LD1WkY9/289-ingest-store-and-display-data-from-40-exchanges-via-tickers)

**Comment by ngauthier** [comment]
Should we also run the audit on the coinbene ticker adapter now?

**Comment by trestrantham** [comment]
Yup! Been testing against that

``` bash
λ yarn cli audit http://nomics-platform-adapter.herokuapp.com/coinbene
yarn run v1.12.3
$ node bin/nomics-platform.js audit http://nomics-platform-adapter.herokuapp.com/coinbene
TAP version 13
1..7
ok 1 - "info" - test #1 in `test/audit.js`
ok 2 - "markets" - test #2 in `test/audit.js`
ok 3 - "trades" - test #3 in `test/audit.js`
ok 4 - "tradesByTimestamp" - test #4 in `test/audit.js`
ok 5 - "ordersSnapshot" - test #5 in `test/audit.js`
ok 6 - "candles" - test #6 in `test/audit.js`
ok 7 - "ticker" - test #7 in `test/audit.js`
# Test run passed!
#   Passed: 7
#   Failed: 0
#   Total:  7
✨  Done in 1.72s.
```

**Comment by ngauthier** [comment]
Oh sorry, I got confused about repositories. I was thinking that after this is merged, we should add coinbene to the test suite on the adapter!

**Pull request merged**
