### PR TITLE
move spec to docs and link

### PR DESCRIPTION
**Pull request by ngauthier**
@claycollins This creates a "doc" folder in the repo for documents, which is standard practice for github repos. I moved the exchange spec to "doc/exchange-integration-specification.md" which will result in a url like this:

```
https://github.com/nomics-crypto/nomics-platform/blob/master/doc/exchange-integration-specification.md
```

We can control the "exchange-platform-integration" part.

We can also control "nomics-platform" but I would recommend against it unless we separate the auditing tool from the specs, which I don't think would be a great developer experience.

### CODE REVIEW

**Comment by ngauthier** [comment]
[Ticker spec (and move specs to github)](https://trello.com/c/xvAQh3TB/41-ticker-spec-and-move-specs-to-github)

**Comment by claycollins** [comment]
@ngauthier does "cryptocurrency-api-exchange-integration" work for you? or "cryptocurrency-exchange-integration" .. would love to get "API" into the slug, but understand if that doesn't make sense (in which case we should go for the second option).

**Comment by ngauthier** [comment]
Sure, that's fine.

**Comment by claycollins** [comment]
@ngauthier cool. Unfortunately, I don't know how to change the URL or I'd do it myself.

**Pull request merged**
